### PR TITLE
bump up 0.0.24

### PR DESCRIPTION
**Pull request by eldesh**
# Improvements

- Update dependencies #112
    - Update tokio and hyper
    - Replace failure crate with thiserror
- Extend IPAMConfig to accept AuxiliaryAddresses for macvlan network
- Restructuring unit tests
    - Reduced number of images used for testing
    - Add test cases

### CODE REVIEW

**Review by hioki — APPROVED** [review]
The https://github.com/Idein/dockworker/pull/121 included in [the difference from the previous version 0.0.23](https://github.com/Idein/dockworker/compare/50b06fa7...release/0.0.24) is a breaking change as it says in the PR text

> Note that this would break existing code using IPAM.Config

but the current major version is `0`,

> https://semver.org/#spec-item-4
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

and the change is only a small part of it, so it looks good.

**Comment by eldesh** [comment]
:pray:

**Comment by dalance** [comment]
Semver compatibility of Rust is difference than the original semver definition.
https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility

> For example, 0.1.0 and 0.1.2 are compatible, but 0.1.0 and 0.2.0 are not. Similarly, 0.0.1 and 0.0.2 are not compatible.

Anything can be changed between 0.0.23 and 0.0.24.
But 0.0.z can't show any information about breaking or not.
So I think bumping up to 0.1.0 may be better at the next time.

**Comment by hioki** [comment]
I just found out about that now. Thanks for the info!

**Pull request merged**
